# v2/cm2_backend.R
# for building the backend


    # new_user_defined = c(
    #     paste("// Generated by covidm", date()),
    #     "",
    #     "#include \"user_defined.h\"",
    #     "#include \"convenience.h\"",
    #     "",
    #     "void CppChanges(const vector<double>& x, Parameters& P)",
    #     "{",
    #     "    (void)x; (void)P;",
    #     paste0("    ", user_defined$model_v2$cpp_changes),
    #     "}",
    #     "",
    #     "double CppLogLikelihood(const vector<double>& x, Reporter& dyn)",
    #     "{",
    #     "    (void)dyn;",
    #     "    double ll = 0.0;",
    #     paste0("    ", user_defined$model_v2$cpp_loglikelihood),
    #     "    return ll;",
    #     "}",
    #     "",
    #     "bool CppObserver(Parameters& P, Randomizer& R, Reporter& dyn, double t, vector<double>& x)",
    #     "{",
    #     "    (void) P; (void) R; (void) dyn; (void) t;",
    #     paste0("    ", user_defined$model_v2$cpp_observer),
    #     "    return true;",
    #     "}"

# I think all of these functions should have access to:
# Parameters& P -- could be const for CppLogLikelihood, but sort of irrelevant as it gets called after the end of simulation, right?
# Randomizer& Rand -- note when called from MCMC, this is initialised with the same seed for each simulation.
# Reporter& Dyn -- change to uppercase -- and improve interface. Can we define some constants "on the fly" to avoid having to do string lookups?
# contents of vector<double>& _x -- as e.g. double theta1 = _x[0];
# observer also needs t.
# So unallowed names for priors are: P, Rand, Dyn, t, ll.


# Build C++ code
cm_source_backend = function(user_defined = NULL)
{
    # Generate user-defined functions
    user_defined_file = paste0(cm_path_, "model_v2/user_defined.cpp");
    new_user_defined = c(
        paste("// Generated by covidm", date()),
        "",
        "#include \"user_defined.h\"",
        "#include \"convenience.h\"",
        "",
        "void CppChanges(const vector<double>& x, Parameters& P)",
        "{",
        "    (void)x; (void)P;",
        paste0("    ", user_defined$model_v2$cpp_changes),
        "}",
        "",
        "double CppLogLikelihood(const vector<double>& x, Reporter& dyn)",
        "{",
        "    (void)dyn;",
        "    double ll = 0.0;",
        paste0("    ", user_defined$model_v2$cpp_loglikelihood),
        "    return ll;",
        "}",
        "",
        "bool CppObserver(Parameters& P, Randomizer& R, Reporter& dyn, double t)",
        "{",
        "    (void) P; (void) R; (void) dyn; (void) t;",
        paste0("    ", user_defined$model_v2$cpp_observer),
        "    return true;",
        "}"
    );

    if (file.exists(user_defined_file)) {
        existing_user_defined = readLines(user_defined_file);
        if (length(existing_user_defined) != length(new_user_defined) || any(existing_user_defined[-1] != new_user_defined[-1])) {
            writeLines(new_user_defined, user_defined_file);
        }
    } else {
        writeLines(new_user_defined, user_defined_file);
    }

    # Build and import source
    sourceCpp(paste0(cm_path_, "/model_v1/corona.cpp"),
              rebuild  = cm_force_rebuild_,
              cacheDir = cm_build_dir_,
              verbose  = cm_build_verbose_)
    sourceCpp(paste0(cm_path_, "/model_v2/Rcpp_interface.cpp"),
              rebuild  = cm_force_rebuild_,
              cacheDir = cm_build_dir_,
              verbose  = cm_build_verbose_)
}
