# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run simulation
#' @export
cm_backend_simulate_v2 <- function(parameters, n_run = 1L, seed = 0L, n_threads = 1L, r_file_out = "") {
    .Call('_covidm_cm_backend_simulate_v2', PACKAGE = 'covidm', parameters, n_run, seed, n_threads, r_file_out)
}

#' Evaluate a distribution
#'
#' @param dist_code Distribution code.
#' @param steps Number of steps.
#' @param xmin,xmax Range over which to evaluate distribution. Leave unspecified for full range of distribution.
#' @export
cm_evaluate_distribution_v2 <- function(dist_code, steps = 101L, xmin = 0, xmax = -1) {
    .Call('_covidm_cm_evaluate_distribution_v2', PACKAGE = 'covidm', dist_code, steps, xmin, xmax)
}

#' Run MCMC
#' @export
cm_backend_mcmc_test <- function(R_base_parameters, params_priors, seed, burn_in, iterations, n_threads, classic_gamma) {
    .Call('_covidm_cm_backend_mcmc_test', PACKAGE = 'covidm', R_base_parameters, params_priors, seed, burn_in, iterations, n_threads, classic_gamma)
}

#' Run optimization
#' @export
cm_backend_optimize_test <- function(R_base_parameters, params_priors, maxeval, ftol_abs, seed, n_threads) {
    .Call('_covidm_cm_backend_optimize_test', PACKAGE = 'covidm', R_base_parameters, params_priors, maxeval, ftol_abs, seed, n_threads)
}

#' Sample from fit
#' @export
cm_backend_sample_fit_test <- function(R_base_parameters, posterior, n, seed) {
    .Call('_covidm_cm_backend_sample_fit_test', PACKAGE = 'covidm', R_base_parameters, posterior, n, seed)
}

#' Get fuction ptr
#' @export
get_cpp_func <- function() {
    .Call('_covidm_get_cpp_func', PACKAGE = 'covidm')
}

#' Use function ptr
#' @export
call_cpp_func <- function(xptr_func, x) {
    .Call('_covidm_call_cpp_func', PACKAGE = 'covidm', xptr_func, x)
}

